# Generated by Django 5.0.3 on 2024-03-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotResponseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField()),
                ('bot_response', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
    ]
