# Generated by Django 5.0.3 on 2024-04-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotungs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('imagen', models.ImageField(upload_to='imagenes_usuarios')),
            ],
        ),
    ]
