# Generated by Django 5.0.3 on 2024-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotungs', '0003_alter_usuario_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(upload_to='./img/usuarios_registrados'),
        ),
    ]
